# Generated by Django 5.2.3 on 2026-09-14 18:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='consent_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='consent_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='device',
            name='hidden_on_child',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='pairing_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='device',
            name='pairing_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='device',
            name='visible_on_child',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='os',
            field=models.CharField(default='Android', max_length=60),
        ),
    ]
